apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-frontend
  template:
    metadata:
      labels:
        app: task-frontend
    spec:
      containers:
      - name: task-frontend
        image: yashuop/task-manager-frontend
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: task-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

