apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-backend
  template:
    metadata:
      labels:
        app: task-backend
    spec:
      containers:
      - name: task-backend
        image: yashuop/task-manager-backend
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: taskdb

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: task-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
