global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

remote_write:
  - url: 'https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push'
    basic_auth:
      username: '${PROMETHEUS_USERNAME}'
      password: '${PROMETHEUS_PASSWORD}'
